weather.settings:
  type: config_object
  label: 'Weather module settings'
  mapping:
    api_key:
      type: string
      label: 'API Key for weather service'
      default: ''
    city:
      type: string
      label: 'Default city name'
      default: 'Lutsk'
