_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: f956f40e-a8e5-44eb-b90c-cbcbf4dbbd69
name: Drupal
mail: drupal-by-Ddev@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/33
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
